version: '3'

services:
  movie-rec:
    build: .
    environment:
      - NODE_ENV=development
      - JWT_SECRET=jwtsecret
    ports:
      - "3001:3001"
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    links:
      - mongo
  mongo:
    image: mongo:3.4
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=password
