version: '3'

services:
  movie-rec:
    build: .
    env_file:
      - .env
    ports:
      - "3001:3001"
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    links:
      - mongo
      - redis
    command: ["watch"]
  mongo:
    image: mongo:3.4
    ports:
      - "27017:27017"
  redis:
    image: redis:3.2
    ports:
      - "6379:6379"
