version: '3'

services:
  movie-rec:
    build: .
    ports:
      - "3001:3001"
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    links:
      - mongo
  mongo:
    image: mongo:3.4
    ports:
      - "27017:27017"
